#!/bin/sh

#
#	A simple generator for a .cpp and .hpp file given a class name
#

if [ -z $1 ]
then
	exit 1;
fi

touch "$1".cpp "$1".hpp

cat << EOF > "$1".hpp
#ifndef $1_HPP
# define $1_HPP

class			$1
{
	public:
		$1(void);
		$1(const $1 &other);
		~$1(void);
		void	operator=(const $1 &other);

	private:
		tmp;
}

#endif
EOF

cat << EOF > "$1".cpp
#include "$1.hpp"

$1::$1(void)
{

}

$1::$1(const $1 &other)
{
	this = other;
}

$1::~$1(void)
{

}

void	$1::operator=(const $1 &other)
{
	tmp;
}
EOF

vim "$1".{c,h}pp -c "bufdo Stdheader" -c ":wqa"
